---
- name: Basic Ansible Playbook
  hosts: machine  # Runs on all hosts defined in the inventory file
  gather_facts: true  # Gather information about the hosts
  tasks:
    - name: Create a simple text file
      file:
        path: /home/bwanwork1/hello_world.txt
        state: touch  # Creates an empty file if it doesn't exist

    - name: Write content to the text file
      copy:
        content: "Hello, world! This is managed by Ansible."
        dest: /home/bwanwork1/hello_world.txt
